BASE_URL = "https://api.trello.com/"

BOARD_ENDPOINT = "1/boards/"
CARD_ENDPOINT = "1/cards"
LISTS_ENDPOINT = "1/boards/{}/lists"
SEARCH_ENDPOINT = "1/search"
# BOARD_ENDPOINT = "1/boards/?name={}&"
# AUTH = "key={}&token={}"
API_KEY = "api_key"
API_TOKEN = "api_token"
DAILY_PLANNER_BOARD = "Project Planner"
